In [1]:
import pandas as pd
import numpy as np
import plotly.express as px

In [2]:
train = pd.read_csv('D:/Projects/Leaf Classification/train.csv')
test = pd.read_csv('D:/Projects/Leaf Classification/test.csv')

In [3]:
test.head()

,id,margin1,margin2,margin3,margin4,margin5,margin6,margin7,margin8,margin9,...,texture55,texture56,texture57,texture58,texture59,texture60,texture61,texture62,texture63,texture64
0,4,0.019531,0.009766,0.078125,0.011719,0.003906,0.015625,0.005859,0.0,0.005859,...,0.006836,0.000000,0.015625,0.000977,0.015625,0.0,0.0,0.000000,0.003906,0.053711
1,7,0.007812,0.005859,0.064453,0.009766,0.003906,0.013672,0.007812,0.0,0.033203,...,0.000000,0.000000,0.006836,0.001953,0.013672,0.0,0.0,0.000977,0.037109,0.044922
2,9,0.000000,0.000000,0.001953,0.021484,0.041016,0.000000,0.023438,0.0,0.011719,...,0.128910,0.000000,0.000977,0.000000,0.000000,0.0,0.0,0.015625,0.000000,0.000000
3,12,0.000000,0.000000,0.009766,0.011719,0.017578,0.000000,0.003906,0.0,0.003906,...,0.012695,0.015625,0.002930,0.036133,0.013672,0.0,0.0,0.089844,0.000000,0.008789
4,13,0.001953,0.000000,0.015625,0.009766,0.039062,0.000000,0.009766,0.0,0.005859,...,0.000000,0.042969,0.016602,0.010742,0.041016,0.0,0.0,0.007812,0.009766,0.007812

In [4]:
train.head()

,id,species,margin1,margin2,margin3,margin4,margin5,margin6,margin7,margin8,...,texture55,texture56,texture57,texture58,texture59,texture60,texture61,texture62,texture63,texture64
0,1,Acer_Opalus,0.007812,0.023438,0.023438,0.003906,0.011719,0.009766,0.027344,0.0,...,0.007812,0.000000,0.002930,0.002930,0.035156,0.0,0.0,0.004883,0.000000,0.025391
1,2,Pterocarya_Stenoptera,0.005859,0.000000,0.031250,0.015625,0.025391,0.001953,0.019531,0.0,...,0.000977,0.000000,0.000000,0.000977,0.023438,0.0,0.0,0.000977,0.039062,0.022461
2,3,Quercus_Hartwissiana,0.005859,0.009766,0.019531,0.007812,0.003906,0.005859,0.068359,0.0,...,0.154300,0.000000,0.005859,0.000977,0.007812,0.0,0.0,0.000000,0.020508,0.002930
3,5,Tilia_Tomentosa,0.000000,0.003906,0.023438,0.005859,0.021484,0.019531,0.023438,0.0,...,0.000000,0.000977,0.000000,0.000000,0.020508,0.0,0.0,0.017578,0.000000,0.047852
4,6,Quercus_Variabilis,0.005859,0.003906,0.048828,0.009766,0.013672,0.015625,0.005859,0.0,...,0.096680,0.000000,0.021484,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.031250

In [5]:
train.isnull().sum()

id           0
species      0
margin1      0
margin2      0
margin3      0
            ..
texture60    0
texture61    0
texture62    0
texture63    0
texture64    0
Length: 194, dtype: int64

In [6]:
train.columns

Index(['id', 'species', 'margin1', 'margin2', 'margin3', 'margin4', 'margin5',
       'margin6', 'margin7', 'margin8',
       ...
       'texture55', 'texture56', 'texture57', 'texture58', 'texture59',
       'texture60', 'texture61', 'texture62', 'texture63', 'texture64'],
      dtype='object', length=194)

In [7]:
train.duplicated().sum()

0

In [23]:
train.info

<bound method DataFrame.info of        id                species   margin1   margin2   margin3   margin4  \
0       1            Acer_Opalus  0.007812  0.023438  0.023438  0.003906
1       2  Pterocarya_Stenoptera  0.005859  0.000000  0.031250  0.015625
2       3   Quercus_Hartwissiana  0.005859  0.009766  0.019531  0.007812
3       5        Tilia_Tomentosa  0.000000  0.003906  0.023438  0.005859
4       6     Quercus_Variabilis  0.005859  0.003906  0.048828  0.009766
..    ...                    ...       ...       ...       ...       ...
985  1575   Magnolia_Salicifolia  0.060547  0.119140  0.007812  0.003906
986  1578            Acer_Pictum  0.001953  0.003906  0.021484  0.107420
987  1581     Alnus_Maximowiczii  0.001953  0.003906  0.000000  0.021484
988  1582          Quercus_Rubra  0.000000  0.000000  0.046875  0.056641
989  1584         Quercus_Afares  0.023438  0.019531  0.031250  0.015625

      margin5   margin6   margin7  margin8  ...  texture55  texture56  \
0    0.011719  0.009766  0.027344      0.0  ...   0.007812   0.000000
1    0.025391  0.001953  0.019531      0.0  ...   0.000977   0.000000
2    0.003906  0.005859  0.068359      0.0  ...   0.154300   0.000000
3    0.021484  0.019531  0.023438      0.0  ...   0.000000   0.000977
4    0.013672  0.015625  0.005859      0.0  ...   0.096680   0.000000
..        ...       ...       ...      ...  ...        ...        ...
985  0.000000  0.148440  0.017578      0.0  ...   0.242190   0.000000
986  0.001953  0.000000  0.000000      0.0  ...   0.170900   0.000000
987  0.078125  0.003906  0.007812      0.0  ...   0.004883   0.000977
988  0.009766  0.000000  0.000000      0.0  ...   0.083008   0.030273
989  0.005859  0.019531  0.035156      0.0  ...   0.000000   0.000000

     texture57  texture58  texture59  texture60  texture61  texture62  \
0     0.002930   0.002930   0.035156   0.000000   0.000000   0.004883
1     0.000000   0.000977   0.023438   0.000000   0.000000   0.000977
2     0.005859   0.000977   0.007812   0.000000   0.000000   0.000000
3     0.000000   0.000000   0.020508   0.000000   0.000000   0.017578
4     0.021484   0.000000   0.000000   0.000000   0.000000   0.000000
..         ...        ...        ...        ...        ...        ...
985   0.034180   0.000000   0.010742   0.000000   0.000000   0.000000
986   0.018555   0.000000   0.011719   0.000000   0.000000   0.000977
987   0.004883   0.027344   0.016602   0.007812   0.000000   0.027344
988   0.000977   0.002930   0.014648   0.000000   0.041992   0.000000
989   0.002930   0.000000   0.012695   0.000000   0.000000   0.023438

     texture63  texture64
0     0.000000   0.025391
1     0.039062   0.022461
2     0.020508   0.002930
3     0.000000   0.047852
4     0.000000   0.031250
..         ...        ...
985   0.000000   0.018555
986   0.000000   0.021484
987   0.000000   0.001953
988   0.001953   0.002930
989   0.025391   0.022461

[990 rows x 194 columns]>

In [8]:
train['species'].value_counts()

Liquidambar_Styraciflua        10
Salix_Intergra                 10
Cotinus_Coggygria              10
Quercus_Rubra                  10
Quercus_Rhysophylla            10
                               ..
Rhododendron_x_Russellianum    10
Quercus_Phillyraeoides         10
Alnus_Sieboldiana              10
Betula_Austrosinensis          10
Salix_Fragilis                 10
Name: species, Length: 99, dtype: int64

In [9]:
train2 = train
train2 = train2.drop(['species'], axis = 1)

In [10]:
species = train['species']

In [11]:
train2.insert(0, 'species', species)

In [12]:
train2.head()

,species,id,margin1,margin2,margin3,margin4,margin5,margin6,margin7,margin8,...,texture55,texture56,texture57,texture58,texture59,texture60,texture61,texture62,texture63,texture64
0,Acer_Opalus,1,0.007812,0.023438,0.023438,0.003906,0.011719,0.009766,0.027344,0.0,...,0.007812,0.000000,0.002930,0.002930,0.035156,0.0,0.0,0.004883,0.000000,0.025391
1,Pterocarya_Stenoptera,2,0.005859,0.000000,0.031250,0.015625,0.025391,0.001953,0.019531,0.0,...,0.000977,0.000000,0.000000,0.000977,0.023438,0.0,0.0,0.000977,0.039062,0.022461
2,Quercus_Hartwissiana,3,0.005859,0.009766,0.019531,0.007812,0.003906,0.005859,0.068359,0.0,...,0.154300,0.000000,0.005859,0.000977,0.007812,0.0,0.0,0.000000,0.020508,0.002930
3,Tilia_Tomentosa,5,0.000000,0.003906,0.023438,0.005859,0.021484,0.019531,0.023438,0.0,...,0.000000,0.000977,0.000000,0.000000,0.020508,0.0,0.0,0.017578,0.000000,0.047852
4,Quercus_Variabilis,6,0.005859,0.003906,0.048828,0.009766,0.013672,0.015625,0.005859,0.0,...,0.096680,0.000000,0.021484,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.031250

In [15]:
test.head()

,id,margin1,margin2,margin3,margin4,margin5,margin6,margin7,margin8,margin9,...,texture55,texture56,texture57,texture58,texture59,texture60,texture61,texture62,texture63,texture64
0,4,0.019531,0.009766,0.078125,0.011719,0.003906,0.015625,0.005859,0.0,0.005859,...,0.006836,0.000000,0.015625,0.000977,0.015625,0.0,0.0,0.000000,0.003906,0.053711
1,7,0.007812,0.005859,0.064453,0.009766,0.003906,0.013672,0.007812,0.0,0.033203,...,0.000000,0.000000,0.006836,0.001953,0.013672,0.0,0.0,0.000977,0.037109,0.044922
2,9,0.000000,0.000000,0.001953,0.021484,0.041016,0.000000,0.023438,0.0,0.011719,...,0.128910,0.000000,0.000977,0.000000,0.000000,0.0,0.0,0.015625,0.000000,0.000000
3,12,0.000000,0.000000,0.009766,0.011719,0.017578,0.000000,0.003906,0.0,0.003906,...,0.012695,0.015625,0.002930,0.036133,0.013672,0.0,0.0,0.089844,0.000000,0.008789
4,13,0.001953,0.000000,0.015625,0.009766,0.039062,0.000000,0.009766,0.0,0.005859,...,0.000000,0.042969,0.016602,0.010742,0.041016,0.0,0.0,0.007812,0.009766,0.007812

In [13]:
X = train2.iloc[:, 1:]
Y = train2.iloc[:, 0]

# Before implementing on the test dataset, lets test our models accuracy

In [18]:
# Splitting the data
from sklearn.model_selection import train_test_split
x_train, x_test,y_train,y_test = train_test_split(X,Y,test_size = (0.3))

# Lets implement Naive Bayes.

In [19]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(x_train, y_train)

GaussianNB()

In [20]:
predNB = gnb.predict(x_test)

In [21]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, predNB)

0.9259259259259259

# Now lets implement the algorithm on our test dataset.

In [14]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X, Y)

GaussianNB()

In [16]:
predNB = gnb.predict(test)

# Let's explore the predictions

In [17]:
predNB

array(['Quercus_Agrifolia', 'Quercus_Afares', 'Acer_Circinatum',
       'Castanea_Sativa', 'Alnus_Viridis', 'Quercus_x_Hispanica',
       'Acer_Opalus', 'Eucalyptus_Glaucescens', 'Quercus_Variabilis',
       'Acer_Rufinerve', 'Phildelphus', 'Quercus_Pontica',
       'Quercus_Pubescens', 'Alnus_Cordata', 'Quercus_Alnifolia',
       'Quercus_Crassifolia', 'Populus_Grandidentata',
       'Quercus_Phillyraeoides', 'Alnus_Sieboldiana', 'Quercus_Palustris',
       'Quercus_Crassipes', 'Quercus_Infectoria_sub',
       'Quercus_Chrysolepis', 'Quercus_Rhysophylla', 'Acer_Circinatum',
       'Quercus_Nigra', 'Eucalyptus_Glaucescens', 'Arundinaria_Simonii',
       'Liquidambar_Styraciflua', 'Quercus_Nigra', 'Quercus_Brantii',
       'Quercus_Pontica', 'Prunus_Avium', 'Quercus_Afares',
       'Acer_Palmatum', 'Liriodendron_Tulipifera', 'Alnus_Viridis',
       'Quercus_Castaneifolia', 'Magnolia_Salicifolia',
       'Tilia_Platyphyllos', 'Acer_Rufinerve', 'Ginkgo_Biloba',
       'Acer_Rufinerve', 'Acer_Saccharinum', 'Quercus_Palustris',
       'Quercus_Nigra', 'Lithocarpus_Edulis', 'Cornus_Controversa',
       'Tilia_Tomentosa', 'Callicarpa_Bodinieri', 'Alnus_Sieboldiana',
       'Acer_Pictum', 'Quercus_Castaneifolia', 'Tilia_Tomentosa',
       'Alnus_Viridis', 'Quercus_x_Hispanica', 'Quercus_Dolicholepis',
       'Ilex_Aquifolium', 'Quercus_Agrifolia', 'Quercus_Canariensis',
       'Rhododendron_x_Russellianum', 'Quercus_Cerris',
       'Cercis_Siliquastrum', 'Quercus_Coccinea', 'Quercus_Hartwissiana',
       'Alnus_Maximowiczii', 'Prunus_X_Shmittii', 'Acer_Pictum',
       'Alnus_Sieboldiana', 'Acer_Palmatum', 'Quercus_Canariensis',
       'Quercus_Chrysolepis', 'Eucalyptus_Neglecta', 'Betula_Pendula',
       'Fagus_Sylvatica', 'Zelkova_Serrata', 'Tilia_Oliveri',
       'Quercus_Variabilis', 'Cotinus_Coggygria', 'Alnus_Cordata',
       'Quercus_Crassipes', 'Quercus_Coccifera', 'Quercus_Vulcanica',
       'Cornus_Macrophylla', 'Acer_Circinatum', 'Acer_Mono',
       'Cornus_Controversa', 'Quercus_Trojana', 'Magnolia_Salicifolia',
       'Cornus_Chinensis', 'Prunus_X_Shmittii', 'Salix_Intergra',
       'Cotinus_Coggygria', 'Cercis_Siliquastrum',
       'Lithocarpus_Cleistocarpus', 'Quercus_Cerris', 'Morus_Nigra',
       'Ulmus_Bergmanniana', 'Acer_Rubrum', 'Pterocarya_Stenoptera',
       'Zelkova_Serrata', 'Quercus_Rhysophylla', 'Acer_Opalus',
       'Alnus_Rubra', 'Fagus_Sylvatica', 'Quercus_Variabilis',
       'Quercus_Brantii', 'Viburnum_Tinus', 'Quercus_Greggii',
       'Quercus_Phellos', 'Tilia_Platyphyllos', 'Tilia_Platyphyllos',
       'Quercus_Imbricaria', 'Eucalyptus_Urnigera', 'Acer_Rufinerve',
       'Rhododendron_x_Russellianum', 'Quercus_Crassifolia',
       'Quercus_x_Turneri', 'Acer_Platanoids', 'Quercus_Chrysolepis',
       'Ilex_Cornuta', 'Ilex_Cornuta', 'Quercus_Crassifolia',
       'Betula_Pendula', 'Tilia_Oliveri', 'Cytisus_Battandieri',
       'Quercus_Agrifolia', 'Rhododendron_x_Russellianum',
       'Magnolia_Heptapeta', 'Cornus_Controversa', 'Cornus_Macrophylla',
       'Acer_Mono', 'Morus_Nigra', 'Quercus_Crassipes',
       'Cornus_Macrophylla', 'Viburnum_x_Rhytidophylloides',
       'Eucalyptus_Neglecta', 'Eucalyptus_Glaucescens',
       'Quercus_Infectoria_sub', 'Quercus_Suber', 'Olea_Europaea',
       'Quercus_Agrifolia', 'Quercus_x_Hispanica', 'Quercus_Dolicholepis',
       'Quercus_Crassifolia', 'Quercus_Alnifolia', 'Ulmus_Bergmanniana',
       'Quercus_Greggii', 'Olea_Europaea', 'Viburnum_Tinus',
       'Ulmus_Bergmanniana', 'Celtis_Koraiensis', 'Quercus_Coccinea',
       'Liquidambar_Styraciflua', 'Quercus_x_Hispanica',
       'Acer_Circinatum', 'Quercus_Cerris', 'Lithocarpus_Edulis',
       'Phildelphus', 'Quercus_Pubescens', 'Celtis_Koraiensis',
       'Quercus_Crassifolia', 'Populus_Nigra', 'Quercus_Semecarpifolia',
       'Cornus_Chinensis', 'Quercus_Semecarpifolia', 'Quercus_Kewensis',
       'Quercus_x_Turneri', 'Quercus_Hartwissiana',
       'Viburnum_x_Rhytidophylloides', 'Quercus_Pubescens',
       'Cercis_Siliquastrum', 'Eucalyptus_Neglecta',
       'Cercis_Siliquastrum', 'Alnus_Maximowiczii', 'Alnus_Cordata',
       'Quercus_Coccifera', 'Tilia_Tomentosa', 'Cytisus_Battandieri',
       'Cornus_Chinensis', 'Arundinaria_Simonii', 'Populus_Grandidentata',
       'Salix_Fragilis', 'Quercus_Canariensis', 'Phildelphus',
       'Acer_Pictum', 'Cornus_Controversa', 'Tilia_Tomentosa',
       'Magnolia_Salicifolia', 'Pterocarya_Stenoptera', 'Salix_Fragilis',
       'Quercus_Phellos', 'Liriodendron_Tulipifera', 'Alnus_Maximowiczii',
       'Quercus_Greggii', 'Ulmus_Bergmanniana', 'Callicarpa_Bodinieri',
       'Sorbus_Aria', 'Eucalyptus_Neglecta', 'Quercus_Greggii',
       'Quercus_Shumardii', 'Acer_Platanoids', 'Quercus_Rubra',
       'Populus_Grandidentata', 'Eucalyptus_Glaucescens',
       'Acer_Saccharinum', 'Quercus_Rubra', 'Salix_Intergra',
       'Populus_Adenopoda', 'Salix_Fragilis', 'Tilia_Oliveri',
       'Alnus_Sieboldiana', 'Acer_Mono', 'Quercus_Coccinea',
       'Acer_Capillipes', 'Viburnum_Tinus', 'Quercus_Nigra',
       'Ginkgo_Biloba', 'Eucalyptus_Neglecta', 'Quercus_Rubra',
       'Sorbus_Aria', 'Quercus_Castaneifolia', 'Populus_Adenopoda',
       'Lithocarpus_Edulis', 'Acer_Pictum', 'Quercus_Crassifolia',
       'Pterocarya_Stenoptera', 'Quercus_Coccifera', 'Tilia_Tomentosa',
       'Quercus_Imbricaria', 'Quercus_Coccifera',
       'Rhododendron_x_Russellianum', 'Salix_Intergra', 'Fagus_Sylvatica',
       'Cotinus_Coggygria', 'Lithocarpus_Cleistocarpus',
       'Callicarpa_Bodinieri', 'Acer_Capillipes', 'Quercus_Pyrenaica',
       'Cytisus_Battandieri', 'Quercus_Nigra', 'Quercus_Palustris',
       'Populus_Adenopoda', 'Quercus_Nigra', 'Ginkgo_Biloba',
       'Salix_Intergra', 'Eucalyptus_Urnigera', 'Quercus_Texana',
       'Ilex_Cornuta', 'Eucalyptus_Urnigera', 'Quercus_Texana',
       'Viburnum_Tinus', 'Prunus_X_Shmittii', 'Quercus_Hartwissiana',
       'Quercus_Chrysolepis', 'Quercus_Greggii', 'Quercus_Cerris',
       'Quercus_Brantii', 'Quercus_Castaneifolia',
       'Quercus_Phillyraeoides', 'Acer_Saccharinum',
       'Quercus_x_Hispanica', 'Quercus_Trojana', 'Morus_Nigra',
       'Eucalyptus_Urnigera', 'Quercus_Ellipsoidalis', 'Betula_Pendula',
       'Cornus_Chinensis', 'Liriodendron_Tulipifera',
       'Quercus_Ellipsoidalis', 'Alnus_Rubra', 'Quercus_Rubra',
       'Liriodendron_Tulipifera', 'Alnus_Viridis', 'Cytisus_Battandieri',
       'Cotinus_Coggygria', 'Quercus_Imbricaria',
       'Eucalyptus_Glaucescens', 'Celtis_Koraiensis',
       'Quercus_Canariensis', 'Quercus_Pyrenaica', 'Quercus_Kewensis',
       'Quercus_Imbricaria', 'Viburnum_x_Rhytidophylloides',
       'Quercus_Shumardii', 'Populus_Adenopoda', 'Tilia_Oliveri',
       'Quercus_Kewensis', 'Cornus_Controversa', 'Cercis_Siliquastrum',
       'Tilia_Tomentosa', 'Quercus_Agrifolia', 'Ilex_Aquifolium',
       'Quercus_Rhysophylla', 'Betula_Austrosinensis',
       'Alnus_Maximowiczii', 'Viburnum_x_Rhytidophylloides',
       'Acer_Circinatum', 'Quercus_Alnifolia', 'Magnolia_Heptapeta',
       'Cornus_Macrophylla', 'Quercus_Alnifolia', 'Olea_Europaea',
       'Quercus_Alnifolia', 'Acer_Mono', 'Quercus_Phillyraeoides',
       'Viburnum_Tinus', 'Quercus_Trojana', 'Rhododendron_x_Russellianum',
       'Acer_Saccharinum', 'Quercus_Ellipsoidalis', 'Quercus_Afares',
       'Betula_Austrosinensis', 'Lithocarpus_Cleistocarpus',
       'Quercus_x_Turneri', 'Ulmus_Bergmanniana', 'Acer_Opalus',
       'Liquidambar_Styraciflua', 'Quercus_Trojana',
       'Quercus_Crassifolia', 'Quercus_Coccinea', 'Quercus_Coccifera',
       'Acer_Capillipes', 'Quercus_Coccifera', 'Quercus_Dolicholepis',
       'Lithocarpus_Edulis', 'Tilia_Platyphyllos',
       'Quercus_Infectoria_sub', 'Quercus_Brantii', 'Populus_Nigra',
       'Castanea_Sativa', 'Populus_Nigra', 'Tilia_Tomentosa',
       'Callicarpa_Bodinieri', 'Acer_Capillipes', 'Ilex_Aquifolium',
       'Salix_Fragilis', 'Magnolia_Salicifolia', 'Quercus_Dolicholepis',
       'Prunus_X_Shmittii', 'Olea_Europaea', 'Acer_Platanoids',
       'Fagus_Sylvatica', 'Sorbus_Aria', 'Quercus_Phillyraeoides',
       'Quercus_Suber', 'Alnus_Rubra', 'Quercus_Vulcanica',
       'Prunus_Avium', 'Acer_Platanoids', 'Quercus_Semecarpifolia',
       'Acer_Mono', 'Cornus_Chinensis', 'Liquidambar_Styraciflua',
       'Phildelphus', 'Acer_Platanoids', 'Quercus_Shumardii',
       'Quercus_Rubra', 'Quercus_Texana', 'Acer_Pictum',
       'Quercus_Crassipes', 'Lithocarpus_Cleistocarpus', 'Phildelphus',
       'Ilex_Aquifolium', 'Quercus_Afares', 'Quercus_Cerris',
       'Quercus_Palustris', 'Populus_Grandidentata', 'Quercus_Coccinea',
       'Olea_Europaea', 'Quercus_Ilex', 'Quercus_x_Hispanica',
       'Zelkova_Serrata', 'Quercus_Trojana', 'Salix_Intergra',
       'Quercus_Greggii', 'Quercus_Texana', 'Alnus_Maximowiczii',
       'Quercus_Semecarpifolia', 'Quercus_Cerris', 'Quercus_Pyrenaica',
       'Pterocarya_Stenoptera', 'Prunus_X_Shmittii', 'Celtis_Koraiensis',
       'Quercus_Pontica', 'Arundinaria_Simonii', 'Ilex_Aquifolium',
       'Pterocarya_Stenoptera', 'Salix_Fragilis', 'Populus_Adenopoda',
       'Betula_Pendula', 'Liquidambar_Styraciflua', 'Alnus_Sieboldiana',
       'Quercus_Castaneifolia', 'Cornus_Controversa', 'Ilex_Cornuta',
       'Populus_Adenopoda', 'Ginkgo_Biloba', 'Eucalyptus_Urnigera',
       'Liriodendron_Tulipifera', 'Acer_Saccharinum', 'Quercus_Phellos',
       'Fagus_Sylvatica', 'Quercus_Crassipes', 'Quercus_Afares',
       'Quercus_Texana', 'Ilex_Cornuta', 'Eucalyptus_Neglecta',
       'Cornus_Chinensis', 'Tilia_Oliveri', 'Quercus_Phellos',
       'Alnus_Maximowiczii', 'Castanea_Sativa', 'Acer_Palmatum',
       'Quercus_x_Turneri', 'Quercus_Agrifolia', 'Quercus_Shumardii',
       'Magnolia_Heptapeta', 'Quercus_Variabilis', 'Ginkgo_Biloba',
       'Quercus_Ilex', 'Liriodendron_Tulipifera', 'Morus_Nigra',
       'Quercus_Phillyraeoides', 'Quercus_Shumardii', 'Acer_Palmatum',
       'Crataegus_Monogyna', 'Quercus_Infectoria_sub', 'Viburnum_Tinus',
       'Celtis_Koraiensis', 'Magnolia_Salicifolia', 'Ilex_Cornuta',
       'Magnolia_Heptapeta', 'Quercus_Cerris', 'Quercus_Phillyraeoides',
       'Quercus_Pyrenaica', 'Quercus_Variabilis', 'Acer_Rubrum',
       'Quercus_Imbricaria', 'Lithocarpus_Cleistocarpus',
       'Acer_Rufinerve', 'Ulmus_Bergmanniana', 'Quercus_Vulcanica',
       'Quercus_Dolicholepis', 'Alnus_Cordata', 'Quercus_Hartwissiana',
       'Morus_Nigra', 'Acer_Mono', 'Prunus_X_Shmittii',
       'Quercus_x_Hispanica', 'Morus_Nigra', 'Quercus_Alnifolia',
       'Acer_Opalus', 'Pterocarya_Stenoptera', 'Prunus_Avium',
       'Quercus_Pyrenaica', 'Quercus_Alnifolia', 'Tilia_Tomentosa',
       'Quercus_Coccinea', 'Rhododendron_x_Russellianum',
       'Quercus_Ellipsoidalis', 'Populus_Grandidentata',
       'Magnolia_Heptapeta', 'Quercus_Ilex', 'Quercus_x_Turneri',
       'Quercus_Pubescens', 'Quercus_Pontica', 'Acer_Rubrum',
       'Quercus_Greggii', 'Quercus_Hartwissiana', 'Quercus_Rubra',
       'Quercus_Ellipsoidalis', 'Quercus_Cerris', 'Cercis_Siliquastrum',
       'Quercus_Crassipes', 'Rhododendron_x_Russellianum',
       'Quercus_Dolicholepis', 'Sorbus_Aria', 'Quercus_Coccinea',
       'Quercus_Trojana', 'Quercus_Pontica', 'Arundinaria_Simonii',
       'Quercus_Vulcanica', 'Acer_Rufinerve', 'Quercus_Ilex',
       'Quercus_Chrysolepis', 'Quercus_Trojana', 'Quercus_Texana',
       'Quercus_Phellos', 'Quercus_Coccifera', 'Eucalyptus_Glaucescens',
       'Betula_Pendula', 'Quercus_Imbricaria', 'Quercus_Ilex',
       'Quercus_Chrysolepis', 'Quercus_Ilex', 'Quercus_Coccifera',
       'Liquidambar_Styraciflua', 'Callicarpa_Bodinieri',
       'Acer_Saccharinum', 'Quercus_Canariensis', 'Sorbus_Aria',
       'Quercus_Hartwissiana', 'Castanea_Sativa', 'Arundinaria_Simonii',
       'Alnus_Cordata', 'Cornus_Macrophylla', 'Quercus_Palustris',
       'Quercus_x_Hispanica', 'Prunus_X_Shmittii', 'Magnolia_Heptapeta',
       'Zelkova_Serrata', 'Betula_Austrosinensis', 'Castanea_Sativa',
       'Populus_Grandidentata', 'Quercus_Pontica', 'Acer_Platanoids',
       'Quercus_Afares', 'Olea_Europaea', 'Ilex_Cornuta',
       'Quercus_Palustris', 'Prunus_Avium', 'Quercus_Vulcanica',
       'Eucalyptus_Glaucescens', 'Quercus_Vulcanica', 'Prunus_Avium',
       'Cotinus_Coggygria', 'Cytisus_Battandieri', 'Quercus_Coccifera',
       'Quercus_Infectoria_sub', 'Quercus_Variabilis',
       'Viburnum_x_Rhytidophylloides', 'Quercus_Ellipsoidalis',
       'Viburnum_x_Rhytidophylloides', 'Quercus_Pyrenaica',
       'Quercus_Suber', 'Quercus_x_Turneri', 'Quercus_Rhysophylla',
       'Alnus_Sieboldiana', 'Acer_Capillipes', 'Eucalyptus_Glaucescens',
       'Morus_Nigra', 'Alnus_Viridis', 'Alnus_Rubra', 'Ilex_Aquifolium',
       'Quercus_x_Hispanica', 'Populus_Nigra', 'Acer_Palmatum',
       'Acer_Palmatum', 'Prunus_Avium', 'Eucalyptus_Urnigera',
       'Castanea_Sativa', 'Quercus_Coccifera', 'Alnus_Sieboldiana',
       'Quercus_Rhysophylla', 'Zelkova_Serrata', 'Acer_Pictum',
       'Betula_Pendula', 'Quercus_Phellos', 'Quercus_Brantii',
       'Ginkgo_Biloba', 'Quercus_Rhysophylla', 'Magnolia_Salicifolia',
       'Quercus_Infectoria_sub', 'Crataegus_Monogyna', 'Tilia_Oliveri',
       'Betula_Austrosinensis', 'Quercus_Ilex',
       'Lithocarpus_Cleistocarpus', 'Alnus_Viridis', 'Tilia_Platyphyllos',
       'Quercus_Shumardii', 'Quercus_Brantii', 'Populus_Nigra',
       'Cotinus_Coggygria', 'Quercus_Afares', 'Betula_Pendula',
       'Lithocarpus_Cleistocarpus', 'Tilia_Platyphyllos',
       'Acer_Capillipes', 'Celtis_Koraiensis', 'Quercus_Canariensis',
       'Alnus_Cordata', 'Sorbus_Aria', 'Magnolia_Salicifolia',
       'Quercus_Suber', 'Quercus_Brantii', 'Callicarpa_Bodinieri',
       'Cytisus_Battandieri', 'Acer_Circinatum', 'Alnus_Rubra',
       'Quercus_Canariensis', 'Quercus_Phillyraeoides',
       'Arundinaria_Simonii'], dtype='<U28')